# Generated by Django 5.0 on 2023-12-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='origin',
            field=models.CharField(choices=[('USR', 'User'), ('AGT', 'Agent'), ('EMP', 'Employee')], default='AGT', max_length=3),
        ),
    ]
