# Generated by Django 5.0 on 2023-12-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
